FROM busybox:latest

LABEL org.opencontainers.image.title="EBAC Docker Hello World"
LABEL org.opencontainers.image.description="Primeira imagem Docker criada para o exercício da EBAC"

CMD ["echo", "Hello World - Julio Orlando"]
